name: first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v6

    - name: welcome message
      run: echo "hello how are you"

    - name: list the files
      run: ls -a 
      
    - name: view readme file
      run: cat README.md