name: third workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the code
      uses: actions/checkout@v6

    - name: running shell script
      run: |
       chmod +x shell-script.sh
       ./shell-script.sh
    - name: view dragon file
      run: cat dragon.txt

  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: Install cowsay
      run: sudo apt-get install cowsay -y
      
    - name: list all cowsay animals
      run: cowsay -l

    - name: make a cow
      run: cowsay -d "Server is down"
